#!/bin/bash

echo -e "$background_left$font_left HOSTNAME        $clear = $background_right$font_right$HOSTNAME $clear"
echo -e "$background_left$font_left TIMEZONE        $clear = $background_right$font_right$TIMEZONE $clear"
echo -e "$background_left$font_left USER            $clear = $background_right$font_right$USER $clear"
echo -e "$background_left$font_left OS              $clear = $background_right$font_right$OS $clear"
echo -e "$background_left$font_left DATE            $clear = $background_right$font_right$DATE $clear"
echo -e "$background_left$font_left UPTIME          $clear = $background_right$font_right$UPTIME $clear"
echo -e "$background_left$font_left UPTIME_SEC      $clear = $background_right$font_right$UPTIME_SEC$clear"
echo -e "$background_left$font_left IP              $clear = $background_right$font_right$IP $clear"
echo -e "$background_left$font_left MASK            $clear = $background_right$font_right$MASK $clear"
echo -e "$background_left$font_left GATEWAY         $clear = $background_right$font_right$GATEWAY $clear"
echo -e "$background_left$font_left RAM_TOTAL       $clear = $background_right$font_right$RAM_TOTAL $clear"
echo -e "$background_left$font_left RAM_USED        $clear = $background_right$font_right$RAM_USED $clear"
echo -e "$background_left$font_left RAM_FREE        $clear = $background_right$font_right$RAM_FREE $clear"
echo -e "$background_left$font_left RAM_FREE        $clear = $background_right$font_right$RAM_FREE $clear"
echo -e "$background_left$font_left SPACE_ROOT      $clear = $background_right$font_right$SPACE_ROOT $clear"
echo -e "$background_left$font_left SPACE_ROOT_USED $clear = $background_right$font_right$SPACE_ROOT_USED $clear"
echo -e "$background_left$font_left SPACE_ROOT_FREE $clear = $background_right$font_right$SPACE_ROOT_FREE $clear"